### ISSUE TITLE
Empty web browser image

### ISSUE THREAD

**Issue by emanuelbuholzer** [iheanyi/social-muter-website#3]
When using my phone (iPhone 6s) to check out the site the web browser image doesn't display any content.

![image](https://cloud.githubusercontent.com/assets/12075322/21290799/8c1d6ce2-c4c8-11e6-9287-867ae2f1c7e6.png)

**Comment by theuiguru** [comment]
Yeah, same for Safari browser doesn't display anything, but not that it matters since it's a Chrome extension tool.
![screen shot 2016-12-18 at 9 58 56 pm](https://cloud.githubusercontent.com/assets/1563057/21299823/4fa323ce-c56d-11e6-8b6b-c92f3db483b7.png)
